#!/usr/bin/ruby

require 'optparse'
require 'csv'
require 'pp'
require 'erb'

options = {}
opt_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__} [options]"
  opts.on('-f', '--file FILE', 'CSV file to convert') { |v| options[:file] = v }
  opts.on('-h', '--help', 'Usage instructions') do
    puts opts
    exit
  end
end

opt_parser.parse!(ARGV)
unless options[:file]
  puts opt_parser.help
  exit
end

path = options[:file]
lines = CSV.read(path)
lines.shift
lines.pop

# ["Longitude", "Latitude", "Household", "Street",
#  "City", "State", "Zip", "Phone", "E-mail",
#  "Location Status"]
#
zones = [
  { id: :manor, zips: [78653], name: "Manor" },
  { id: :elgin, zips: [78621, 78659], name: "Elgin" },
  { id: :mueller, zips: [78702, 78722, 78723], name: "Mueller" },
  { id: :johnny_morris, zips: [78724, 78725], name: "Johnny Morris" },
  { id: :rosedale, zips: [78705, 78751], name: "Rosedale" },
  { id: :highland, zips: [78752], name: "Highland" },
  { id: :copperfield, zips: [78753], name: "Copperfield" },
  { id: :pioneer_crossing, zips: [78754], name: "Pioneer Crossing" },
  { id: :metric, zips: [78758], name: "Metric" }
]

by_zip = {}
by_status = {}
lines.each do |line|
  re = /^(\d{5})/
  zip = 'Unknown'
  matches = re.match(line[6])
  if matches
    zip = matches[1]
  end
  by_zip[zip] = [] unless by_zip.include?(zip)
  by_zip[zip] << line

  by_status[line[9]] = [] unless by_status.include?(line[9])
  by_status[line[9]] << line
end

# Collect the zones by zip code
by_zone = {}
zones.sort_by { |v| v[:name] }.each do |zone|
  by_zone[zone[:name]] = [] unless by_zone.include?(zone[:name])
  zips = by_zip.keys.map(&:to_i) & zone[:zips]
  if zips.length > 0
    zips.each do |z|
      by_zone[zone[:name]].concat(by_zip[z.to_s])
    end
    by_zone[zone[:name]].sort_by! { |m| m[2] }
  end
end

# Group the members not in the ward
not_in_ward = {}
zips_not_in_ward = by_zip.keys.map(&:to_i) - zones.map { |z| z[:zips] }.flatten

zips_not_in_ward.each do |z|
  zip = z.to_s
  not_in_ward[zip] = by_zip[zip] if by_zip.include?(zip)
end

folders = [
  { items: by_zone, name: "Zones" },
  { items: not_in_ward, name: "Out of Ward" },
  { items: by_zip, name: "Member by Zip" },
  { items: by_status, name: "Members by Status" }
]

template = File.read('./template.kml.erb')
contents = ERB.new(template).result(binding)

base_file = "wardmap"
kml_file = "#{base_file}.kml"
kmz_file = "#{base_file}.kmz"

File.open(kml_file, 'w') do |file|
  file.write(contents)
end

%x{/usr/bin/zip #{kmz_file} #{kml_file}}

File.unlink(kml_file)
